import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Resize Image",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <main className="p-8">{children}</main>
      </body>
    </html>
  );
}
